name: Build and Deploy Docs

on:
  push:
    branches: [main] # 当推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # # 1. 拉取代码
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # # 2. 设置 Node.js 环境
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "22" # 根据你的项目调整

      # # 3. 缓存 npm 依赖（加速构建）
      # - name: Cache dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      # # 4. 安装依赖
      # - name: Install dependencies
      #   run: npm install

      # # 5. 构建静态网站
      # - name: Build docs
      #   run: npm run docs:build

      # 6. 部署到 Ubuntu 服务器（使用 tar + scp）
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Ubuntu Server
        run: |

          # 压缩 dist 目录
          tar -czf dist.tar.gz -C dist .

          # 上传压缩包到服务器
          scp  -o StrictHostKeyChecking=no \
            dist.tar.gz \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/nfs-data/passjava/passjava-learning/

          # 在服务器上解压并清理
          ssh -i -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} \
            "cd /nfs-data/passjava/passjava-learning && tar -xzf dist.tar.gz && rm dist.tar.gz"
